language: scala
jdk: oraclejdk8
scala: 2.12.7

jobs:
  include:
    - stage: test
      script: sbt scalafmtCheck scalafmtSbtCheck
      name: "Formatting check"
    - script: sbt test scripted
      name: "Tests run"
    - stage: publish
      script: sbt ^publish
      name: "Publish"

stages:
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = lightbend/sbt-paradox-dependencies AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "NSfCqmKtunk+Xbrx5X94JMcHeY7hxtH/7/5eAInEctlArDAdGlYo23BFW3SU4/eHEZjj5J8gVr65s79sQwt1x4Et9J9+jloKA0syrj/h7phPSyB4gcZI57726zffdP6muueWL9JtlZzfIX7dMDTHaLUKXwBeXQCMiC0q2/ke+LQR6JhLWEA734ZBqtT+ECmspzahs7MkDZqNZK4QS447UEoICbuDimPFT7mt7CiDvdYm90cCifQIQ2TyO0Q4eOf9h403RfWRJUnAzGJYMSNWyHkBeEeg/sMB89ApCFttgV3v1o6bA2oSvkke7LLbrlgEKshY8gHlzKt0163aVAVFBCniXVmxGtiqrin8wQ5/4YOh+AkZDN+u0BqGwe5GgK5p1Qu9OjrKK0GRy+0N/J8Vi1A4vcarXsRWqRe6ve2MxdGtaN0mbL04FXjKJN+8MDlCaSB2mFi1fgepg1OLWgxuhnrwC240osW/acm4ROM6Ze4Z6yY6IQYO6ratgmjN1gNixtBMT2glRnWqUVpHdrNJEPHLYGU7oM42U7a/Mei/mcxp98Zaw9Rvs2mJpb5ElXbhyID9H+t3Pk2Bz4gliGP8Z03uF5k9dTftLeAB+iWKlsgBruJ6ywhHm5VIfYZ+LCSGQcS0ZIZuagbB0nOSBl0uSPxwsXUPZAFAFKuDSDL9D1Q="
    # travis encrypt BINTRAY_PASS=...
    - secure: "OmGlKM1l4uZjZEA7gFvd9jOXwg6uwm2UrXgHO16he0s6q7OlRSklJX+6ap/M2bB+HG109OOZMpqy6pz/m3+n8o4ixsRXRhVy/HLBCKQ4bQaLoeIADqolEyteROjG19BbmmydsFXrezJGKiTaPqgAA7DUi0simdvYwT7tJDTUkM6vqCLu6SUK4/KGSF5rRCyAm7eNcCtYqJue6KxJmfMfVF2ZtgTxON9nd6I+htUeVGRMETKzGcuEk5fuin64EmG0lale5EvBYj6WH2vrcxQ51RbXC0YDwmSUuDzUaXcATIJWKbDb6bxRxr1AkELiTnJ8zDlY+L0l6RB0ILVFxhqAAtyibyhTQlW9qnCH2lDL1bxRmpIu4j6nvpcZNi4HHqVyzBxsWAvTEfALct6IPExeje14ZDudq4wBQsRixH9Scc/BKNDGML4Z6Q6Ff2OYhF7DyM/5uKZ5dAcgz5Lyb9Uwpy5mkjhOoRtkNwxT6vMYghxw9nWzBs6j3J4VxhVs925zkTnN2pmtgI/qp46u4G3KFsIyuaxYfXZKMRjnCTj0IsvuQJ/7DIS1TfUGvoIHgOYkrHImFs7T/+7G8b14V1j+s9bFy5uI8r4gpocAaVe8HN9HxkzOsmXJFsqvrcS27CJ+cPspCqgebj4E+38jeyJUb6dbvC6W8zCjyanaa88xvvQ="
