language: scala
jdk: oraclejdk8
scala: 2.12.7

jobs:
  include:
    - stage: test
      script: sbt scalafmtCheck scalafmtSbtCheck
      name: "Formatting check"
    - script: sbt test scripted
      name: "Tests run"
    - stage: publish
      script: sbt ^publish
      name: "Publish"

stages:
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = lightbend/sbt-paradox-dependencies AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "cmYnSXvHKV8O4uODStJMvSZHPy2QALoIsmLY/rjUYv/zMr1VnWwTpobcF1sjkx1saWKst7tk9dv9V7UtsnXzzwkl0BvqkyjYPro3OdbtjMqZ1ejKOhalA1y5gqd33F294zAyPKDUk9cIBj6zSlMxCYrUfOPj1WxNc13N0hTHmpvNYu6D9Ata+KS4E+i6kCj3tMB+/ly0ytfLeoyy1qXABHnbn7aAN3c9KW+YG8+CeQD4WVixNjHmH+bEHkP0I/uQGc0irBMGVLgE/50D7kpFMlfZY7WdZbzu4O2stp0g7I0DlqKn9q8VRY52Tp/Pe3DSwx6elQczy38lz2CDDbk7KeBYrcVa6dR+BtBMTAerKHiRjfAf5PPdueRzZ6np1MZxnZeP1/HFZdCrYwEHDrhYmx7saVd74QAoz6Osubw3AhYwNKTdplqdkq3rW9hZhUrEUhgmGCZUBhhmJAKuJg3VKdLJcSPocoK2AAq7lEU03RzQneFwISCamnGEaucPJBUEvKjoNcJKJpvff0oTMXbwSIO5GW6ytf/BTNjrl/ZDqjSxX2AeqYLwMHLBLLsiWjgQ9zFdxie1GUutI2CwONYN39Tmm5t39lqyNnPHr+3mcEvO/Mccu/CuaU28IH2d1PaHauOmOhXqnHRAm7Hw4Rn9WRQ+bsFdyojwaFbJZ7iCwug="
    # travis encrypt BINTRAY_PASS=...
    - secure: "dT/pQ6Z/CAFaMqfydMmj3Gxr9oGPqIXb7WQsjKLc7+vG3ISgbSntPS+iCIIB3ygQ0N2NETJlS148wvBmSdvgFktVQQnXyEgNX+7S/g+v7KwrvIJLHoonmE4omUL0qlAiMdlG2vLghaAZHZQZViYvHK9ZaIk6Whf+2LdBkSydN5tATknhQ6iHhqp+0Few7PKP8D3giCAXnLqw++37p8mRkR8XwtQfiJ7dpOYn/Smp8IpLgT7RxkkDfs8fFrxCuRMZs6i7VHwUDBSB1GY34q20E8x4zE/S/Bgp2bbPsDChmsYwhonq26gyFxJldSXpSwvpS1Z1jRtAlZsb8FWPWLlXC23HBHC94WMtRzBe6lAfTl2VFyjAmXy7A+gqdATyMETz2xL2YpkQNcMkptFxHqN2DBKsMd8h8Y4zeBzsfDrj2L9Cjm+JPvD93LmKQk+BWAr+grfjL+GVVsJVpQfcZaAdlhcfQVuFIYyzs67/nKnQkyzMNsyQUHynXZDvrKawyTJvJaq4RmM7DadWxzR9Q9AeOkJUz1kCe0yTQt/LT1PVN28BTHQZJR7GbRWu23QN/C926C1ujMZjb5KHegYpnaGZ7Z489+KsQ88+KuniOoAZ3QCdWb2pFkX0ngPTLQpYDOor9rm3Jaxn0N90YHgTS+mCHIj+3TZZerI18xvSZBziKjA="
